### ISSUE TITLE
 2019/10/10 第155回 フロントエンドMTG 議事録

### ISSUE THREAD

**Issue by kogai** [feedforce/frontend-meeting#10]

**Comment by jinmayamashita** [comment]
## `tsc-watch --onSuccess`
https://www.npmjs.com/package/tsc-watch

tsc から compile された js ファイルを（特に express など）更新する時に、nodemon などを使っていたけど、`tsc-watch --onSuccess node dist/index.js` だけでよかった。:sweat_smile:

## next の `src` directory が support されるということ
https://nextjs.org/blog/next-9-1
server 側で page 単位の component を描画するため存在した default directory の `pages` が
`src/pages` で利用できるよという話。特に今まで不便なことはなかったけど、source ファイルは `src` ディレクトリに！という方にはいいかもと思った。

**Comment by zenoplex** [comment]
## Pornhub のデベロッパーインタビュー

https://davidwalsh.name/pornhub-interview

## Domino pizza 訴訟を振り返って（まだ裁判続行中）

- https://www.w3.org/TR/WCAG20/
- https://chrome.google.com/webstore/detail/chromevox-classic-extensi/kgejglhpjiefppelpmljglcjbhoiplfn
- 目隠しをして ChromeVox 使ってテストするサイトもあるとか

## SICP in Javascript

https://sicp.comp.nus.edu.sg/

## gpu.js

https://gpu.rocks/

**Comment by mashabow** [comment]
## Bundle Analyzer

- [Bundle Analyzer](https://www.bundle-analyzer.com/)
- 📖 [Quick Start - Bundle Analyzer](https://docs.bundle-analyzer.com/docs/quick-start/)

(M) マネージャーのリポジトリにも入れてみた。GitHub Actions でビルド。

```yaml
name: Bundle Analyzer
on: push
jobs:
  bundle-analyzer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.3
      - name: Install node modules
        run: |
          yarn install
          yarn add @bundle-analyzer/cli
      - name: Build by webpack and upload stats to bundle-analyzer.com
        run: |
          yarn -s build:webpack --json \
            | $(yarn bin)/bundle-analyzer --token $BUNDLE_ANALYZER_TOKEN
        env:
          BUNDLE_ANALYZER_TOKEN: ${{ secrets.BUNDLE_ANALYZER_TOKEN }}
```

ただし、Size compare (Size diff) が表示されない… 😢
